development: &default
  host: localhost
  adapter: postgresql
  database: angular_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: angular_test

production:
  <<: *default
  database: angular_production
